language: ruby
rvm:
  - 2.7.2

before_install:
  - gem install bundler

script: 
  - bundle install
  - bundle exec rake load_test_csv RAILS_ENV=test
  - bundle exec rspec

services:
  - postgresql

cache: bundler

os:
  -linux
  -osx
